### ISSUE TITLE
Unable to build on macOS 13.4 (Intel)

### ISSUE THREAD

**Issue by leshik** [Blockstream/greenlight#168]
I can't make it work with any Python version (tried 3.8, 3.9, 3.10 & 3.11). `pip install -U gl-client` works fine, then `pip install --extra-index-url=https://us-west2-python.pkg.dev/c-lightning/greenlight-pypi/simple/ -U glcli` fails with
```
Caused by:
  error inheriting `anyhow` from workspace root manifest's `workspace.dependencies.anyhow`

Caused by:
  failed to find a workspace root
```
I also tried `pip install git+https://github.com/Blockstream/greenlight#subdirectory=libs/gl-client-py -U glcli`, but this fails too:
```
ERROR: Could not find a version that satisfies the requirement glcli (from versions: none)
ERROR: No matching distribution found for glcli
```

**Comment by cdecker** [comment]
There was an issue with `glcli` referencing the private repo we used before open-sourcing. Since the `gl-client` version was not cross-compiled to all platforms downloading it will cause the package to attempt to recompile. That fails because the Rust source was rewritten, and paths no longer match.

I have pushed a new version of `glcli` which now references the public `gl-client` package instead, which is cross-compiled for a variety of platforms, so a new installation should work now.
