### ISSUE TITLE
Relai: User can not send payments

### ISSUE THREAD

**Issue by roeierez** [Blockstream/greenlight#424]
Node ID: 03228ef6f7fbe4db9512589dcbef842fb6d95d050fdf0b09d3f2b677b86eeb834a

https://github.com/breez/breez-sdk-relai/issues/39

**Comment by cdecker** [comment]
Quick update from the internal discussions:

 - The HTLC addition for the first HTLC times out, causing us to disconnect, and not find a path for any of the later attempts.
 - `pay` then eventually fails, because it has ground the amount into many tiny HTLCs that it still can't find a path for
 - Root cause analysis:
   - Signer could be on a high latency, low bandwidth link (low bandwidth would have to be <0.5KB/s)
   - Node <> peer is a high latency link (bandwidth is less of an issue here)
   - Peer is slow in acknowledging the HTLC

We're looking into the specifics for this user, and also discussing increasing the timeout to reduce chances of such a thing occurring.
