### ISSUE TITLE
Relai: Payment failure

### ISSUE THREAD

**Issue by roeierez** [Blockstream/greenlight#425]
Node ID: 020ee42d02323fa7d10300bb7148c93e1bcb7944bc7510c605d03acfc5f9b41bb1
Timestamp: Thursday 02/05 at 17:22 CET

https://github.com/breez/breez-sdk-relai/issues/31

**Comment by cdecker** [comment]
Relaying the discussion from the private tracker (to keep user privacy intact):

 - The user attempted several times to spend the entirety of their balance to a node in the network that is not their peer
 - This kind of draining a channel requires special support in the software as we need to pay the routiong fees to forwarding nodes, which is not being taken into account by the user.
 - Closing this issue as it has more to do with the user trying something that LN does not support, rather than an issue with GL or CLN.
